#!/usr/bin/env python3
"""
build.py — Script para compilar voice_clone.py como ejecutable portable.

Uso:
  python build.py              # Compilar para la plataforma actual
  python build.py --clean      # Limpiar archivos temporales antes de compilar
  python build.py --onefile    # Generar ejecutable unico (mas lento, ~1.5-2GB)
  python build.py --onedir    # Generar carpeta con archivos (mas rapido, recomendado)
"""

import os
import sys
import shutil
import subprocess
import argparse
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).resolve().parent
BUILD_DIR = SCRIPT_DIR / 'build'
DIST_DIR = SCRIPT_DIR / 'dist'
SPEC_FILE = SCRIPT_DIR / 'voice_clone.spec'
ENTRY_POINT = SCRIPT_DIR / 'voice_clone.py'

# Hidden imports that PyInstaller might miss
HIDDEN_IMPORTS = [
    'torch',
    'torchaudio',
    'encodec',
    'transformers',
    'transformers.models',
    'transformers.models.bert',
    'transformers.models.hubert',
    'einops',
    'scipy',
    'scipy.special',
    'scipy.io',
    'scipy.io.wavfile',
    'numpy',
    'huggingface_hub',
    'tqdm',
    'bark',
    'bark.api',
    'bark.generation',
    'bark.model',
    'bark.model_fine',
    'hubert',
    'hubert.hubert_manager',
    'hubert.pre_kmeans_hubert',
    'hubert.customtokenizer',
]

# Data files to include (relative to script dir)
DATA_FILES = [
    ('bark/assets', 'bark/assets'),
    ('bark/__init__.py', 'bark'),
    ('bark/api.py', 'bark'),
    ('bark/generation.py', 'bark'),
    ('bark/model.py', 'bark'),
    ('bark/model_fine.py', 'bark'),
    ('hubert/__init__.py', 'hubert'),
    ('hubert/hubert_manager.py', 'hubert'),
    ('hubert/pre_kmeans_hubert.py', 'hubert'),
    ('hubert/customtokenizer.py', 'hubert'),
]


def clean():
    """Remove build artifacts."""
    print("Cleaning build artifacts...")
    for d in [BUILD_DIR, DIST_DIR]:
        if d.exists():
            shutil.rmtree(d)
            print(f"  Removed {d}/")
    for f in [SPEC_FILE]:
        if f.exists():
            f.unlink()
            print(f"  Removed {f}")
    print("Clean complete.")


def build_spec_content(onefile: bool) -> str:
    """Generate PyInstaller .spec file content."""
    datas = []
    for src, dst in DATA_FILES:
        src_path = SCRIPT_DIR / src
        if src_path.exists():
            datas.append(f"    (r'{src_path}', r'{dst}')")

    datas_str = ',\n'.join(datas)
    mode = 'ONEFILE' if onefile else 'ONEDIR'

    return f"""# -*- mode: python ; coding: utf-8 -*-
# voice_clone.spec — Generated by build.py

a = Analysis(
    [r'{ENTRY_POINT}'],
    pathex=[r'{SCRIPT_DIR}'],
    binaries=[],
    datas=[
{datas_str},
    ],
    hiddenimports={HIDDEN_IMPORTS},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PIL',
        'cv2',
        'IPython',
        'jupyter',
        'notebook',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='voice_clone',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
"""


def build(onefile: bool = False):
    """Build the executable using PyInstaller."""
    print(f"\nBuilding {'onefile' if onefile else 'onedir'} executable...")

    # Check PyInstaller is installed
    try:
        import PyInstaller
        print(f"PyInstaller version: {PyInstaller.__version__}")
    except ImportError:
        print("Error: PyInstaller not installed.")
        print("Install with: pip install pyinstaller")
        sys.exit(1)

    # Generate spec file
    spec_content = build_spec_content(onefile)
    SPEC_FILE.write_text(spec_content, encoding='utf-8')
    print(f"Generated: {SPEC_FILE}")

    # Build command
    cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--noconfirm',
        '--clean',
        str(SPEC_FILE),
    ]

    print(f"\nRunning: {' '.join(cmd)}")
    print("=" * 60)

    result = subprocess.run(cmd, cwd=str(SCRIPT_DIR))

    print("=" * 60)

    if result.returncode == 0:
        exe_dir = DIST_DIR
        print(f"\nBuild successful!")
        print(f"Output: {exe_dir}/")

        # List output files
        if exe_dir.exists():
            print("\nGenerated files:")
            for f in sorted(exe_dir.iterdir()):
                size_mb = f.stat().st_size / (1024 * 1024)
                print(f"  {f.name} ({size_mb:.1f} MB)")
    else:
        print(f"\nBuild failed with return code: {result.returncode}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Build voice_clone as portable executable"
    )
    parser.add_argument('--clean', action='store_true', help='Clean build artifacts first')
    parser.add_argument('--onefile', action='store_true', help='Build as single file (slower, larger)')
    parser.add_argument('--onedir', action='store_true', default=True, help='Build as directory (faster, default)')

    args = parser.parse_args()

    if args.clean:
        clean()
        return

    onefile = args.onefile and not args.onedir
    build(onefile=onefile)


if __name__ == '__main__':
    main()
