# -*- mode: python ; coding: utf-8 -*-
# voice_clone.spec — Generated by build.py

a = Analysis(
    [r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\voice_clone.py'],
    pathex=[r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice'],
    binaries=[],
    datas=[
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\bark\assets', r'bark/assets'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\bark\__init__.py', r'bark'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\bark\api.py', r'bark'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\bark\generation.py', r'bark'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\bark\model.py', r'bark'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\bark\model_fine.py', r'bark'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\hubert\__init__.py', r'hubert'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\hubert\hubert_manager.py', r'hubert'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\hubert\pre_kmeans_hubert.py', r'hubert'),
    (r'G:\PROJECTS\bark-with-voice-clone\app_clone_voice\hubert\customtokenizer.py', r'hubert'),
    ],
    hiddenimports=['torch', 'torchaudio', 'encodec', 'transformers', 'transformers.models', 'transformers.models.bert', 'transformers.models.hubert', 'einops', 'scipy', 'scipy.special', 'scipy.io', 'scipy.io.wavfile', 'numpy', 'huggingface_hub', 'tqdm', 'bark', 'bark.api', 'bark.generation', 'bark.model', 'bark.model_fine', 'hubert', 'hubert.hubert_manager', 'hubert.pre_kmeans_hubert', 'hubert.customtokenizer'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PIL',
        'cv2',
        'IPython',
        'jupyter',
        'notebook',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='voice_clone',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
